<?php
/**
 * SPRE WooCommerce hooks override handler.
 *
 * @package SPRE\Frontend
 */

declare(strict_types=1);

namespace SPRE\Frontend;

use SPRE\Recommendation\Engine;
use SPRE\Core\Container;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class WooCommerceHooks
 *
 * Hooks into WooCommerce template actions to override layouts with smart recommendations.
 */
class WooCommerceHooks {

	/**
	 * Recommendation Engine.
	 *
	 * @var Engine
	 */
	private Engine $engine;

	/**
	 * Constructor.
	 *
	 * @param Engine $engine Engine instance.
	 */
	public function __construct( Engine $engine ) {
		$this->engine = $engine;
	}

	/**
	 * Bind WooCommerce filters and actions.
	 */
	public function register(): void {
		// Read settings
		$settings = get_option( 'spre_settings', [] );
		$replace_related = isset( $settings['replace_default_related'] ) ? (bool) $settings['replace_default_related'] : true;

		if ( $replace_related ) {
			// 1. Remove core related products template call
			remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_related_products', 20 );

			// 2. Inject our smart engine instead
			add_action( 'woocommerce_after_single_product_summary', [ $this, 'output_smart_related_products' ], 20 );

			// 3. Filter core related product query to empty to suppress default theme-level widgets
			add_filter( 'woocommerce_related_products', '__return_empty_array', 100 );
		}

		// Inject Frequently Bought Together in single product tabs/summary details if configured
		$show_fbt_summary = isset( $settings['show_fbt_in_summary'] ) ? (bool) $settings['show_fbt_in_summary'] : true;
		if ( $show_fbt_summary ) {
			add_action( 'woocommerce_after_single_product_summary', [ $this, 'output_fbt_widget' ], 15 );
		}
	}

	/**
	 * Output related products generated by our similarity weighting algorithm.
	 */
	public function output_smart_related_products(): void {
		global $product;

		if ( ! $product ) {
			return;
		}

		$settings = get_option( 'spre_settings', [] );
		$limit    = isset( $settings['related_limit'] ) ? (int) $settings['related_limit'] : 4;

		$context = [
			'product_id' => $product->get_id(),
			'limit'      => $limit,
		];

		// Run engine similarity
		$results = $this->engine->get_recommendations( 'related', $context );

		$this->render_widget(
			'related',
			esc_html__( 'Related Products', 'smart-product-recommendation-engine' ),
			$results['products'],
			$results['ab_test_id'],
			$results['ab_variation']
		);
	}

	/**
	 * Output Frequently Bought Together widget under details summary.
	 */
	public function output_fbt_widget(): void {
		global $product;

		if ( ! $product ) {
			return;
		}

		$settings = get_option( 'spre_settings', [] );
		$limit    = isset( $settings['fbt_limit'] ) ? (int) $settings['fbt_limit'] : 3;

		$context = [
			'product_id' => $product->get_id(),
			'limit'      => $limit,
		];

		// Run engine FBT
		$results = $this->engine->get_recommendations( 'fbt', $context );

		$this->render_widget(
			'fbt',
			esc_html__( 'Frequently Bought Together', 'smart-product-recommendation-engine' ),
			$results['products'],
			$results['ab_test_id'],
			$results['ab_variation']
		);
	}

	/**
	 * Render widget helper.
	 */
	private function render_widget(
		string $widget_type,
		string $title,
		array $products,
		?int $ab_test_id,
		?string $ab_variation
	): void {
		if ( empty( $products ) ) {
			return;
		}

		$template_path = SPRE_PLUGIN_DIR . 'templates/recommendation-widget.php';
		if ( file_exists( $template_path ) ) {
			include $template_path;
		}
	}
}
